version: "3"
services:
  dremio:
    image: dremio/dremio-oss:24.2.5
    ports:
      - 9047:9047 # UI
      - 31010:31010 # ODBC clients
      - 32010:32010 # Arrow Flight clients
      - 2181:2181   # ZooKeeper
      - 45678:45678 # internode communication
    volumes:
      - /data/dremio/data/:/opt/dremio/data/
      - /data/dremio/conf/:/opt/dremio/conf/
    restart: unless-stopped
    networks:
      local_internal:
        ipv4_address: 172.20.80.2

  mysql:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwd@123
    networks:
      local_internal:
        ipv4_address: 172.20.80.3

networks:
  local_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.80.0/24
